services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rails_react_practice_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: bash -c "bundle install && rails db:create && rails db:migrate && rails db:seed && rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0' -p 3001"
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rails_react_practice_development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - RAILS_ENV=development

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  frontend_node_modules: { }